all:
		javac FuzzySearch.java
		java FuzzySearch
		rm *.class

s: 
	javac Server.java
	javac ClientManager.java
	javac Packet.java
	javac UserInfo.java
	javac FuzzySearch.java
	java Server

c:
	javac Login.java
	javac Client.java
	javac Packet.java
	javac UserInfo.java
	javac FuzzySearch.java
	java Login

clean:
	rm *.class
	rm output/*
